export const DIRECTORY_KEY = 'viziunea.directory.v1';
export const NEEDS_KEY = 'viziunea.needs.v1';
export const SUGGESTIONS_KEY = 'viziunea.suggestions.v1';
export const NOTIFICATIONS_KEY = 'viziunea.notifications.v1';

export function readList(key, fallback = []) {
  try { const value = localStorage.getItem(key); return value ? JSON.parse(value) : fallback; }
  catch { return fallback; }
}
export function writeList(key, value) { localStorage.setItem(key, JSON.stringify(value)); }

const created = '2026-09-01T10:00:00.000Z';
export const demoDirectory = [
  { id:'demo-foto-constanta', slug:'foto-constanta', title:'Fotograf pentru proiecte creative', description:'Fotograf de portret și documentar disponibil pentru proiecte și evenimente locale.', item_type:'person', domain:'creative_services', value_type:'people_skills', tags:['fotograf','fotografie','portret','eveniment','foto'], city:'Constanța', county:'Constanța', region:'Sud-Est', country:'România', location_mode:'travels', service_area_scope:'county', travel_radius_km:80, contact_url:'https://example.org/fotograf', status:'published', created_at:created },
  { id:'demo-space-bucuresti', slug:'spatiu-evenimente-bucuresti', title:'Spațiu pentru evenimente independente', description:'Sală modulară pentru expoziții, performance și întâlniri comunitare.', item_type:'space', domain:'art', value_type:'resources_infrastructure', tags:['spațiu','eveniment','expoziție','sală','locație'], city:'București', county:'București', region:'București-Ilfov', country:'România', location_mode:'fixed', service_area_scope:'city', travel_radius_km:null, contact_url:'https://example.org/spatiu', status:'published', created_at:created },
  { id:'demo-ceramica-cluj', slug:'atelier-ceramica-cluj', title:'Atelier de ceramică', description:'Ateliere introductive de ceramică pentru grupuri mici.', item_type:'course', domain:'art', value_type:'knowledge', tags:['atelier','ceramică','curs','artă','învățare'], city:'Cluj-Napoca', county:'Cluj', region:'Nord-Vest', country:'România', location_mode:'fixed', service_area_scope:'city', travel_radius_km:null, contact_url:'https://example.org/ceramica', status:'published', created_at:created },
  { id:'demo-hiking-macin', slug:'hiking-macin', title:'Hiking în Munții Măcinului', description:'Tur ghidat pe trasee din Munții Măcinului, cu accent pe natură și patrimoniu local.', item_type:'experience', domain:'tourism', value_type:'experiences_services', tags:['hiking','drumeție','natură','Munții Măcinului','Măcin','tur ghidat'], location_label:'Munții Măcinului', city:'Greci', county:'Tulcea', region:'Sud-Est', country:'România', location_mode:'fixed', service_area_scope:'nearby', travel_radius_km:null, contact_url:'https://example.org/macin', status:'published', created_at:created },
  { id:'demo-cultural-constanta', slug:'tur-cultural-constanta', title:'Experiență culturală în Constanța', description:'Plimbare ghidată prin poveștile și arhitectura multiculturală a orașului.', item_type:'experience', domain:'tourism', value_type:'experiences_services', tags:['experiență culturală','tur','patrimoniu','Constanța','istorie'], city:'Constanța', county:'Constanța', region:'Sud-Est', country:'România', location_mode:'fixed', service_area_scope:'city', travel_radius_km:null, contact_url:'https://example.org/tur-cultural', status:'published', created_at:created },
  { id:'demo-mentor-branding', slug:'mentor-branding-online', title:'Mentorat de branding', description:'Sesiuni individuale online pentru clarificarea identității și poziționării unui proiect.', item_type:'service', domain:'creative_services', value_type:'people_skills', tags:['consultant branding','branding','mentor','consultanță','online','remote'], city:'București', county:'București', region:'București-Ilfov', country:'România', location_mode:'remote', service_area_scope:'online', travel_radius_km:null, contact_url:'https://example.org/mentorat', status:'published', created_at:created },
  { id:'demo-sound-tulcea', slug:'kit-sunet-tulcea', title:'Kit mobil de sunet', description:'Echipament audio compact disponibil pentru împrumut în județul Tulcea.', item_type:'resource', domain:'creative_services', value_type:'resources_infrastructure', tags:['echipament','sunet','audio','microfon','resursă'], city:'Tulcea', county:'Tulcea', region:'Sud-Est', country:'România', location_mode:'travels', service_area_scope:'county', travel_radius_km:60, contact_url:'https://example.org/kit-sunet', status:'published', created_at:created },
  { id:'demo-scenography', slug:'colaborare-scenografie', title:'Oportunitate de colaborare în scenografie', description:'Căutăm colaboratori pentru dezvoltarea unor instalații scenografice temporare.', item_type:'project', domain:'art', value_type:'opportunities', tags:['colaborare','scenografie','proiect','oportunitate','decor'], city:'București', county:'București', region:'București-Ilfov', country:'România', location_mode:'hybrid', service_area_scope:'national', travel_radius_km:null, contact_url:'https://example.org/scenografie', status:'published', created_at:created },
  { id:'demo-semnal', slug:'semnal-spatii-culturale', title:'Inițiativa Semnal pentru spații culturale', description:'Inițiativă de documentare a spațiilor culturale independente și a nevoilor lor.', item_type:'initiative', domain:'cultural_intervention', value_type:'signals_action', tags:['intervenție culturală','semnal','inițiativă','spații culturale','educație'], city:'', county:'', region:'', country:'România', location_mode:'location_independent', service_area_scope:'national', travel_radius_km:null, contact_url:'https://example.org/semnal', status:'published', created_at:created },
  { id:'demo-video-remote', slug:'editor-video-remote', title:'Editor video pentru proiecte', description:'Editare și post-producție video, colaborare complet remote.', item_type:'service', domain:'creative_services', value_type:'experiences_services', tags:['editor video','video','editare','remote','film'], city:'', county:'', region:'', country:'România', location_mode:'remote', service_area_scope:'online', travel_radius_km:null, contact_url:'https://example.org/video', status:'published', created_at:created },
];

export const demoNeeds = [
  { id:'demo-need-photo-constanta', requester_id:'demo:ana@example.test', intent:'find', query:'fotograf pentru proiect în Constanța', city:'Constanța', county:'Constanța', country:'România', location_preference:'fixed', max_distance_km:null, remote_ok:false, status:'open', created_at:'2026-09-08T12:00:00.000Z' },
  { id:'demo-need-edit-video', requester_id:'demo:mihai@example.test', intent:'find', query:'editor video, remote este ok', city:'Cluj-Napoca', county:'Cluj', country:'România', location_preference:'remote', max_distance_km:null, remote_ok:true, status:'open', created_at:'2026-09-10T12:00:00.000Z' },
];
