export function createPublicViews({ navbar, footer, esc, path, profile, feed, demoResults, feedPosts, exploreCategories, pageContent, directionContent }) {
  const home = () => `${navbar()}<main class="public-home"><section class="home-hero"><span class="page-kicker">Viziunea · Oameni · Spații · Idei · Împreună</span><h1>Un ecosistem creativ care crește împreună.</h1><p>Viziunea aduce într-un singur loc oamenii, proiectele, spațiile și oportunitățile care pot transforma ideile în realitate.</p><div class="home-actions"><a class="account-cta" href="/exploreaza#oameni">Explorează ecosistemul <span>→</span></a><a class="home-secondary" href="/despre">Descoperă Viziunea</a></div></section><section class="home-pillars"><article><span class="home-pillar-icon">◌</span><h2>Oameni care se găsesc</h2><p>Profiluri, roluri și interese care fac conexiunile relevante.</p></article><article><span class="home-pillar-icon">✦</span><h2>Idei care prind formă</h2><p>Proiecte, evenimente și resurse adunate într-un ecosistem viu.</p></article><article><span class="home-pillar-icon">⌂</span><h2>Locuri deschise</h2><p>Spații și contexte unde comunitatea poate lucra împreună.</p></article></section><section class="home-invitation"><span class="page-kicker">Intră în ecosistem</span><h2>Descoperă ce există. Găsește ce ți se potrivește. Contribuie cu ce știi.</h2><a class="home-text-link" href="/auth">Intră în cont <span>→</span></a></section></main>${footer()}`;
  const shell = (title, cls = '') => {
    const directionKey = path().split('/').pop();
    const [intro, items] = pageContent[path()] || (directionContent[directionKey] && [directionContent[directionKey][0], directionContent[directionKey].slice(1)]) || ['Structură de pagină', ['Conținutul acestei pagini va fi construit ulterior']];
    return `${navbar()}<main class="page ${cls}"><span class="page-kicker">Page shell</span><h1>${esc(title)}</h1><p class="page-intro">${esc(intro)}</p><ul class="page-outline">${items.map(item => `<li>${esc(item)}</li>`).join('')}</ul></main>${footer()}`;
  };

  const explore = () => {
    const active = exploreCategories.some(([id]) => id === location.hash.slice(1)) ? location.hash.slice(1) : 'oameni';
    const results = demoResults[active];
    const locations = ['București', 'Cluj-Napoca', 'Iași', 'Brașov'];
    const countByLocation = locations.reduce((counts, city, cityIndex) => {
      counts[city] = results.filter((_, index) => index % locations.length === cityIndex).length;
      return counts;
    }, {});
    const defaultCity = locations.includes(profile.city) ? profile.city : '';
    const defaultDistance = Number(feed.radius) || 100;
    const locationOptions = `<option value="">Toate locațiile (${results.length})</option>${Object.entries(countByLocation).filter(([, count]) => count).map(([city, count]) => `<option value="${city}" ${city === defaultCity ? 'selected' : ''}>${city} (${count})</option>`).join('')}`;
    const distances = [50, 100, 250, 500];
    const authors = ['Radu Călin', 'Zametheea Popescu', 'Mara Enache'];
    return `${navbar()}<main class="page explore-page"><span class="page-kicker">Page shell</span><h1>Explorează</h1><p class="page-intro">Ce există în ecosistem</p><div class="explore-pills" role="tablist">${exploreCategories.map(([id, label]) => `<a class="explore-pill ${id === active ? 'selected' : ''}" href="/exploreaza#${id}" role="tab" aria-selected="${id === active}">${label}</a>`).join('')}</div><section class="explore-filter-bar"><label>Locație<select id="explore-location" name="location" class="explore-filter" data-filter="location">${locationOptions}</select></label><label>Distanță<select id="explore-distance" name="distance" class="explore-filter" data-filter="distance" ${defaultCity ? '' : 'disabled'}><option value="">Orice distanță</option>${distances.map(distance => `<option value="${distance}" ${defaultCity && distance === defaultDistance ? 'selected' : ''}>până la ${distance} km</option>`).join('')}</select></label><button class="filter-reset" data-explore-reset type="button">Resetează</button><span class="filter-count" data-explore-count>${results.length} rezultate</span><label class="explore-name-filter">Opțional · caută după nume<input id="explore-search" name="search" class="explore-search" type="search" placeholder="Nume sau titlu"></label></section><section class="demo-results"><span class="page-kicker">Demo results · date fictive</span><h2>${esc(exploreCategories.find(([id]) => id === active)[1])}</h2><div class="result-grid">${results.map((item, index) => `<article class="result-card" data-result data-location="${locations[index % locations.length]}"><span>0${index + 1}</span><strong>${esc(item.title)}</strong><button class="result-author" data-explore-author="${active}" data-detail-index="${index}" type="button">Publicat de ${esc(item.author_name || authors[index % authors.length])}</button><b>${esc(item.meta)}</b><small>${esc(item.desc)}</small><button class="person-more" data-explore-detail="${active}" data-detail-index="${index}" type="button">Vezi mai multe <span>→</span></button></article>`).join('')}</div><p class="empty-explore" hidden>Nu există rezultate pentru combinația aleasă.</p></section></main>${footer()}`;
  };

  const profileView = () => {
    const roles = ['Creator', 'Trainer', 'Participant', 'Voluntar', 'Partner', 'Gazdă de spațiu'];
    const interests = ['Artă', 'Educație', 'Experiențe', 'Turism', 'Evenimente', 'Proiecte', 'Spații', 'Oportunități'];
    const cities = ['București', 'Cluj-Napoca', 'Iași', 'Brașov', 'Sibiu'];
    const radiusOptions = [50, 100, 250, 500];
    return `${navbar()}<main class="page profile-page"><span class="page-kicker">Page shell · Demo profile</span><section class="profile-hero"><div class="large-avatar">Z</div><div><h1>Zametheea</h1><p>zametheea@demo.viziunea.ro</p></div></section><section class="profile-selectors"><article><span class="page-kicker">Roluri</span><h2>Ce roluri te reprezintă?</h2><p>Selectează sau deselectează oricând rolurile care te reprezintă.</p><div class="profile-choices">${roles.map(role => `<button class="profile-choice ${profile.roles.includes(role) ? 'selected' : ''}" data-profile-type="roles" data-profile-value="${role}" type="button">${role}</button>`).join('')}</div></article><article><span class="page-kicker">Interese</span><h2>Ce te interesează?</h2><p>Alege domeniile pe care vrei să le urmărești în profilul tău.</p><div class="profile-choices">${interests.map(interest => `<button class="profile-choice ${profile.interests.includes(interest) ? 'selected' : ''}" data-profile-type="interests" data-profile-value="${interest}" type="button">${interest}</button>`).join('')}</div></article><article class="profile-location"><span class="page-kicker">Locație</span><h2>Care este orașul tău?</h2><p>Îl folosim ca punct de plecare pentru recomandările locale.</p><label>Oraș<select id="profile-city" name="city" data-profile-city>${cities.map(city => `<option ${city === profile.city ? 'selected' : ''}>${city}</option>`).join('')}</select></label><label>Câți km de jur împrejur vrei să vezi?<select id="profile-radius" name="radius" data-profile-radius>${radiusOptions.map(radius => `<option value="${radius}" ${Number(feed.radius) === radius ? 'selected' : ''}>${radius} km</option>`).join('')}</select></label></article></section><section class="profile-structure"><article><span class="page-kicker">Profil</span><h2>Profilul meu</h2><ul><li>Nume și date de contact</li><li>Scurtă prezentare</li><li>Disponibilitate</li><li>Linkuri publice</li></ul></article></section></main>${footer()}`;
  };

  const feedView = () => {
    const choices = ['Artă', 'Educație', 'Experiențe', 'Turism', 'Evenimente', 'Proiecte', 'Spații'];
    const radiusOptions = [10, 25, 50, 100, 250];
    const posts = feedPosts.filter(post => (!feed.interests.length || feed.interests.some(interest => (post.interests || [post.interest]).includes(interest))) && (post.distance === 0 || post.distance <= Number(feed.radius)));
    return `${navbar()}<main class="page feed-page"><span class="page-kicker">Zona personală</span><h1>Feed</h1><p class="page-intro">Postări din comunitate, potrivite intereselor și zonei tale.</p><div class="feed-preferences">${choices.map(choice => `<button class="feed-choice ${feed.interests.includes(choice) ? 'selected' : ''}" data-feed-interest="${choice}" type="button">${choice}</button>`).join('')}</div><section class="feed-location"><div><span class="page-kicker">Recomandări locale</span><strong>${esc(feed.city)}</strong><small>Oraș preluat automat din profil</small></div><label>Raza față de oraș<select id="feed-radius" name="radius" data-feed-radius>${radiusOptions.map(radius => `<option value="${radius}" ${Number(feed.radius) === radius ? 'selected' : ''}>${radius} km</option>`).join('')}</select></label></section><section class="community-feed"><header><div><span class="page-kicker">Comunitatea ta</span><h2>${posts.length} ${posts.length === 1 ? 'postare relevantă' : 'postări relevante'}</h2></div><small>Date demonstrative</small></header><div class="feed-posts">${posts.length ? posts.map(post => `<article class="feed-post"><div class="feed-post-author"><span class="feed-post-avatar">${post.initial}</span><div><button type="button" class="feed-post-author-link" data-feed-author="${feedPosts.indexOf(post)}">${esc(post.author)}</button><small>${esc(post.role)} · ${esc(post.time)}</small></div><span class="feed-post-distance">${post.distance ? `${post.distance} km · ` : ''}${esc(post.city)}</span></div><div class="feed-post-content"><span class="feed-post-tag">${esc(post.interest)}</span><h3>${esc(post.title)}</h3><p>${esc(post.body)}</p></div><footer><button type="button" data-feed-action="interested">Sunt interesat(ă), vreau să știu mai multe</button><div><button type="button" data-feed-action="like" aria-label="Like">♡</button><button type="button" aria-label="Salvează">♡</button><button type="button" aria-label="Distribuie">↗</button></div></footer></article>`).join('') : `<div class="feed-empty"><strong>Nu sunt încă postări pentru combinația aleasă.</strong><span>Extinde raza sau selectează încă un interes.</span></div>`}</div></section></main>${footer()}`;
  };

  const auth = () => `${navbar()}<main class="auth-page"><section class="auth-card"><a class="site-logo" href="/admin">Viziunea<span>✳</span></a><span class="page-kicker">Comunitatea Viziunea · Demo</span><h1>Intră în cont</h1><p>Alege unul dintre cele două conturi demo separate.</p><form id="auth-form"><label>Nume<input name="display_name" autocomplete="name" value="Zametheea"></label><label>Email<input name="email" type="email" autocomplete="email" required value="zametheea@demo.viziunea.ro"></label><button class="account-cta" type="submit">Continuă <span>→</span></button></form><div class="demo-login-divider"><span>conturi demo</span></div><button class="demo-login-button" type="button" data-demo-login="zametheea">Zametheea Popescu · profil principal <span>→</span></button><button class="demo-login-button" type="button" data-demo-login="radu">Radu Călin · profil demo 2 <span>→</span></button><p class="auth-message"></p></section></main>`;

  return { home, shell, explore, profile: profileView, feed: feedView, auth };
}
