import { getCurrentUser, signInWithEmail, signOut } from './services/auth.js';

const app = document.querySelector('#app');
let currentUser = null, authNotice = '', mobileOpen = false;
const ROUTES = {'/':'Acasă','/despre':'Despre','/directii':'Direcții','/exploreaza':'Explorează','/resurse':'Resurse','/feed':'Feed','/profil':'Profil','/setari':'Setări','/notificari':'Notificări','/mesaje':'Mesaje','/admin':'Admin'};
const DIRECTIONS = [['/directii/servicii-creative-suport','Servicii Creative și Suport'],['/directii/educatie','Educație'],['/directii/arta','Artă'],['/directii/turism','Turism'],['/directii/interventie-culturala','Intervenție Culturală'],['/directii/spatii-art-hub','Spații / Art-Hub']];
const path = () => location.pathname.replace(/\/+$/, '') || '/';
const go = url => { history.pushState({},'',url); mobileOpen=false; render(); };
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link = (url,label,extra='') => `<a class="nav-link ${path()===url?'active':''} ${extra}" href="${url}">${label}</a>`;
const directionsMenu = () => DIRECTIONS.map(([u,l])=>link(u,l)).join('');
const exploreMenu = () => `${link('/despre','Despre')}${link('/directii','Direcții')}${link('/resurse','Resurse')}`;
const exploreCategories = [['oameni','Oameni'],['proiecte','Proiecte'],['experiente','Experiențe'],['evenimente','Evenimente'],['oportunitati','Oportunități'],['spatii','Spații']];
const exploreCategoriesMenu = () => exploreCategories.map(([id,label]) => `<a class="explore-category" href="/exploreaza#${id}">${label}</a>`).join('');
const PAGE_CONTENT = {
  '/': ['Intrare + orientare', ['Descoperă Viziunea', 'Alege direcția potrivită', 'Intră în zona personală']],
  '/despre': ['Poveste + rădăcini', ['Zametheea', 'Societatea Viziunea', 'Istoric', 'Valori + poveste']],
  '/directii': ['Ce face Viziunea', DIRECTIONS.map(([, label]) => label)],
  '/exploreaza': ['Ce există în ecosistem', exploreCategories.map(([, label]) => label).concat(['Filtre: direcție · locație · perioadă'])],
  '/resurse': ['Biblioteca ecosistemului', ['Ghiduri', 'Modele', 'Arhivă proiecte', 'Contacte utile']],
  '/feed': ['Zona personală', ['Feed personalizat', 'Actualizări din ecosistem']],
  '/profil': ['Identitate + preferințe', ['Identitatea utilizatorului', 'Preferințe pentru Feed']],
  '/setari': ['Controlul contului', ['Setări profil', 'Preferințe notificări', 'Deconectare']],
  '/notificari': ['Activitatea contului', ['Notificări', 'Actualizări importante']],
  '/mesaje': ['Comunicare', ['Mesaje', 'Conversații']]
};
const DEMO_RESULTS = {
  oameni: ['Profiluri din comunitate', 'Roluri și interese', 'Conexiuni relevante'],
  proiecte: ['Proiecte în dezvoltare', 'Arhivă de proiecte', 'Colaborări deschise'],
  experiente: ['Ateliere și întâlniri', 'Experiențe culturale', 'Activități în comunitate'],
  evenimente: ['Evenimente viitoare', 'Evenimente găzduite', 'Calendarul ecosistemului'],
  oportunitati: ['Oportunități de colaborare', 'Roluri disponibile', 'Apeluri și propuneri'],
  spatii: ['Spații Viziunea', 'Locații partenere', 'Spații disponibile']
};
const profileMenu = () => `${link('/profil','Profil')}${link('/setari','Setări')}<button class="dropdown-action" data-signout>Deconectare</button>`;
function navbar(){
  const auth=Boolean(currentUser), nav=auth?`${link('/feed','Feed')}<div class="nav-dropdown"><button class="nav-link nav-trigger" type="button">Explorează</button><div class="dropdown-panel explore-panel">${exploreCategoriesMenu()}</div></div><div class="nav-dropdown"><button class="nav-link nav-trigger" type="button">Direcții</button><div class="dropdown-panel">${directionsMenu()}</div></div>${link('/resurse','Resurse')}`:`${link('/','Acasă')}${link('/despre','Despre')}<div class="nav-dropdown"><button class="nav-link nav-trigger" type="button">Direcții</button><div class="dropdown-panel">${directionsMenu()}</div></div><div class="nav-dropdown"><button class="nav-link nav-trigger" type="button">Explorează</button><div class="dropdown-panel explore-panel">${exploreCategoriesMenu()}</div></div>${link('/resurse','Resurse')}`;
  const mobile=auth?`${link('/feed','Feed')}${link('/exploreaza','Explorează')}${link('/directii','Direcții')}${link('/resurse','Resurse')}`:`${link('/','Acasă')}${link('/despre','Despre')}${link('/directii','Direcții')}${link('/exploreaza','Explorează')}${link('/resurse','Resurse')}`;
  return `<header class="site-header"><a class="site-logo" href="/">Viziunea<span>✳</span></a><nav class="desktop-nav">${nav}</nav><div class="header-actions">${auth?`${link('/mesaje','Mesaje','compact')}${link('/notificari','Notificări','compact')}<div class="nav-dropdown profile-dropdown"><button class="nav-link nav-trigger profile-link" type="button"><span class="profile-avatar">Z</span></button><div class="dropdown-panel">${profileMenu()}</div></div>`:`<a class="account-cta" href="/auth">Intră în cont</a>`}</div><button class="menu-toggle" data-menu aria-label="Meniu">☰</button></header>${mobileOpen?`<nav class="mobile-nav">${mobile}${auth?`${link('/mesaje','Mesaje')}${link('/notificari','Notificări')}${link('/profil','Profil')}<div class="mobile-profile"><span>Cont · Zametheea</span>${link('/setari','Setări')}<button class="mobile-signout" data-signout>Deconectare</button></div>`:''}<div class="mobile-directions"><span>Direcții</span>${directionsMenu()}</div><div class="mobile-explore"><span>Explorează</span>${exploreCategoriesMenu()}</div></nav>`:''}`;
}
const footer=()=>`<footer class="site-footer"><span>Viziunea</span><span>Oameni · Spații · Idei · Împreună</span></footer>`;
const DIRECTION_CONTENT = { 'servicii-creative-suport':['La spațiu','În deplasare','Remote'], 'educatie':['Cursuri','Mentorat','Formare profesională (practică)'], 'arta':['Proiectele membrilor','Hand-made la comandă','Spectacole produse','Spectacole găzduite','Resurse'], 'turism':['Locații partenere','Conferințe','Tabere & proiecte'], 'interventie-culturala':['Valori & viziuni','Propuneri legislative','Arhivă proiecte'], 'spatii-art-hub':['Studio Viziunea','Studio Cartierul Urban','Grădina Popânzac','Magazin ZAmulet','Sala de dans / cursuri','Ateliere & rezidențe'] };
const shell=(title,cls='')=>{const directionKey=path().split('/').pop();const [intro,items]=PAGE_CONTENT[path()]|| (DIRECTION_CONTENT[directionKey]&&['Structura direcției',DIRECTION_CONTENT[directionKey]]) || ['Structură de pagină',['Conținutul acestei pagini va fi construit ulterior']];return `${navbar()}<main class="page ${cls}"><span class="page-kicker">Page shell</span><h1>${esc(title)}</h1><p class="page-intro">${esc(intro)}</p><ul class="page-outline">${items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></main>${footer()}`;};
function exploreView(){const active=exploreCategories.some(([id])=>id===location.hash.slice(1))?location.hash.slice(1):'oameni';const results=DEMO_RESULTS[active];return `${navbar()}<main class="page explore-page"><span class="page-kicker">Page shell</span><h1>Explorează</h1><p class="page-intro">Ce există în ecosistem</p><div class="explore-pills" role="tablist">${exploreCategories.map(([id,label])=>`<a class="explore-pill ${id===active?'selected':''}" href="/exploreaza#${id}" role="tab" aria-selected="${id===active}">${label}</a>`).join('')}</div><section class="demo-results"><span class="page-kicker">Demo results</span><h2>${esc(exploreCategories.find(([id])=>id===active)[1])}</h2><div class="result-grid">${results.map((item,index)=>`<article class="result-card"><span>0${index+1}</span><strong>${item}</strong><small>Conținut demonstrativ pentru această categorie</small></article>`).join('')}</div></section><p class="explore-filters">Filtre: direcție · locație · perioadă</p></main>${footer()}`;}
function profileView(){return `${navbar()}<main class="page profile-page"><span class="page-kicker">Page shell · Demo profile</span><section class="profile-hero"><div class="large-avatar">Z</div><div><h1>Zametheea</h1><p>zametheea@demo.viziunea.ro</p></div></section><section class="profile-structure"><article><span class="page-kicker">Identitate</span><h2>Profilul meu</h2><ul><li>Nume și date de contact</li><li>Roluri și interese</li><li>Despre mine</li></ul></article><article><span class="page-kicker">Prezență</span><h2>Despre mine</h2><ul><li>Scurtă prezentare</li><li>Oraș și disponibilitate</li><li>Linkuri publice</li></ul></article></section></main>${footer()}`;}
function feedView(){const choices=['Oameni','Proiecte','Experiențe','Evenimente','Oportunități','Spații'];return `${navbar()}<main class="page feed-page"><span class="page-kicker">Page shell · Demo feed</span><h1>Feed</h1><p class="page-intro">Alege ce vrei să apară în Feed.</p><div class="feed-preferences">${choices.map((choice,index)=>`<button class="feed-choice ${index<2?'selected':''}" type="button">${choice}</button>`).join('')}</div><section class="demo-results"><span class="page-kicker">Demo results</span><h2>Conținut pentru tine</h2><div class="result-grid"><article class="result-card"><span>01</span><strong>Recomandări din ecosistem</strong><small>Rezultatele vor fi personalizate în funcție de alegerile tale.</small></article><article class="result-card"><span>02</span><strong>Actualizări relevante</strong><small>Aici vor apărea proiecte, evenimente și oportunități.</small></article></div></section></main>${footer()}`;}
function authView(){return `<main class="auth-page"><section class="auth-card"><a class="site-logo" href="/">Viziunea<span>✳</span></a><span class="page-kicker">Comunitatea Viziunea · Demo</span><h1>Intră în cont</h1><p>Continuă cu profilul demo Zametheea pentru a vedea zona personală.</p><form id="auth-form"><label>Nume<input name="display_name" autocomplete="name" value="Zametheea"></label><label>Email<input name="email" type="email" autocomplete="email" required value="zametheea@demo.viziunea.ro"></label><button class="account-cta" type="submit">Continuă <span>→</span></button></form><p class="auth-message">${esc(authNotice)}</p></section></main>`;}
function adminView(){return `<header class="site-header admin-header"><a class="site-logo" href="/">Viziunea<span>✳</span></a><span class="admin-badge">ADMIN</span><a href="/" class="nav-link">Înapoi la site</a></header><main class="admin-shell"><span class="page-kicker">Admin</span><h1>Zona de administrare</h1><p>Panoul pentru gestionarea informațiilor Viziunea.</p><div class="admin-placeholder"><strong>Funcțiile de administrare rămân disponibile aici.</strong><span>Structura publică nouă nu afectează această zonă.</span></div></main>`;}
function render(){document.body.classList.toggle('admin-mode',path()==='/admin');if(path()==='/admin')app.innerHTML=adminView();else if(path()==='/auth')app.innerHTML=authView();else if(path()==='/exploreaza')app.innerHTML=exploreView();else if(path()==='/profil')app.innerHTML=profileView();else if(path()==='/feed')app.innerHTML=feedView();else {const title=ROUTES[path()]||DIRECTIONS.find(([u])=>u===path())?.[1]||'Pagină';app.innerHTML=shell(title,path().slice(1).replaceAll('/','-')||'home');}bind();}
function bind(){app.querySelector('[data-menu]')?.addEventListener('click',()=>{mobileOpen=!mobileOpen;render();});app.querySelectorAll('a[href]').forEach(a=>a.addEventListener('click',e=>{const u=a.getAttribute('href');if(u?.startsWith('/')){e.preventDefault();go(u);}}));app.querySelectorAll('.feed-choice').forEach(button=>button.addEventListener('click',()=>button.classList.toggle('selected')));app.querySelector('[data-signout]')?.addEventListener('click',async()=>{await signOut();currentUser=null;go('/');});app.querySelector('#auth-form')?.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{const r=await signInWithEmail(d.email,d.display_name);currentUser=r.user||await getCurrentUser();authNotice=r.mode==='otp'?'Ți-am trimis un link pe email.':'';go('/feed');}catch(err){authNotice=err.message||'Autentificarea nu a reușit.';render();}});}
window.addEventListener('popstate',render);void getCurrentUser().then(u=>{currentUser=u;render();});
